<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Legal Entity Information
    |--------------------------------------------------------------------------
    |
    | Identifying information for the legal entity operating this SaaS. Used
    | in site footers, legal pages (Terms, Privacy), and Organization JSON-LD
    | structured data. The full registered street address is intentionally
    | not stored or published on the public site; it lives in CEIDG and on
    | invoices generated by Stripe/Cashier.
    |
    */

    'legal_name' => 'B-apps Wojciech Rybiński',
    'nip' => '8133481592',
    'regon' => '364036823',
    'city' => 'Warsaw',
    'country' => 'Poland',
    'country_code' => 'PL',

];
